version: "3.3"
services:
  
  server1:
    build: ./server
    image: server
    container_name: Server-1
    ports:
      - 8001:5000
    restart: always
    deploy:
      replicas: 1
    networks: 
      testnetwork:
        aliases:
          - server1


  server2:
    image: server
    container_name: Server-2
    ports:
      - 8002:5000
    restart: always
    deploy:
      replicas: 1
    networks: 
      testnetwork:
        aliases:
          - server2


  server3:
    image: server
    container_name: Server-3
    ports:
      - 8003:5000
    restart: always
    deploy:
      replicas: 1
    networks: 
      testnetwork:
        aliases:
          - server3



  nginx:
    build: ./load-balancer
    container_name: nginx
    links:
      - server1
      - server2
      - server3
    ports:
      - 80:80
    networks: 
      testnetwork:
        aliases:
          - nginx

networks:
  testnetwork:
