version: "3.3"
name: loadbalancer
services:
  web:
    build: ./server
    expose:
      - 8080
    restart: always
    deploy:
      mode: replicated
      replicas: 6
    networks: 
      - internal_network


  nginx:
    build: ./load-balancer
    ports:
      - 80:80
    restart: always
    networks: 
      - internal_network
    depends_on:
      - web

networks:
  internal_network:
    driver: bridge
