# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x04test\"\x1f\n\x0fGreetingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"$\n\x10GreetingResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2A\n\x07Greeter\x12\x36\n\x05Greet\x12\x15.test.GreetingRequest\x1a\x16.test.GreetingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GREETINGREQUEST']._serialized_start=23
  _globals['_GREETINGREQUEST']._serialized_end=54
  _globals['_GREETINGRESPONSE']._serialized_start=56
  _globals['_GREETINGRESPONSE']._serialized_end=92
  _globals['_GREETER']._serialized_start=94
  _globals['_GREETER']._serialized_end=159
# @@protoc_insertion_point(module_scope)
